---
name: Test
on:
  pull-request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Call Dagger Test Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          # assumes a Go project
          args: test --source=.
