apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "tapservice.fullname" . }}
  labels:
    {{- include "tapservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: tap
  selector:
    {{- include "tapservice.selectorLabels" . | nindent 4 }}
