# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_server/adqlparser.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgrpc_server/adqlparser.proto\"\x1c\n\x0b\x41\x44QLRequest\x12\r\n\x05query\x18\x01 \x01(\t\",\n\x0bSQLResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0e\n\x06parsed\x18\x02 \x01(\t23\n\nADQLParser\x12%\n\x05Parse\x12\x0c.ADQLRequest\x1a\x0c.SQLResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.adqlparser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADQLREQUEST']._serialized_start=32
  _globals['_ADQLREQUEST']._serialized_end=60
  _globals['_SQLRESPONSE']._serialized_start=62
  _globals['_SQLRESPONSE']._serialized_end=106
  _globals['_ADQLPARSER']._serialized_start=108
  _globals['_ADQLPARSER']._serialized_end=159
# @@protoc_insertion_point(module_scope)
