---
name: Deploy Staging
on:
  release:
    types: [prereleased]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    name: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_STAGING }}
          aws-region: us-east-1
          output-credentials: true
          unset-current-credentials: true
      -
        name: Call Dagger Deploy Function
        uses: dagger/dagger-for-github@v5
        env:
          GH_TOKEN: ${{secrets.TAP_TOKEN}} 
        with:
          version: "latest"
          verb: call
          args: deploy-helm-charts --username=tapservice-chart --password=env:GH_TOKEN --helm-values=ssm:tapservice-values-staging --version=24.9.0 --dry-run=true
          workdir: ./ci
