name: Publish
on:
  push:
    branches: [aws/test]

permissions:
  contents: read
  packages: write
  
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Call Dagger Publish Function
        uses: dagger/dagger-for-github@v5
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "latest"
          verb: call
          args: publish-images --rootDir=.. --username=${{github.actor}} --password=${{secrets.GITHUB_TOKEN}} --tags=rc
          workdir: ./ci
      -
        name: Call Dagger Publish Helm Charts Function
        uses: dagger/dagger-for-github@v5
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "latest"
          verb: call
          args: publish-helm-charts --rootDir=.. --username=${{github.actor}} --password=${{secrets.GITHUB_TOKEN}}
          workdir: ./ci